import pandas as pd
from fpdf import FPDF
from datetime import datetime

# Step 1: Read data
data = pd.read_csv("data.csv")

# Step 2: Analyze data
average_score = data["Score"].mean()
highest_score = data["Score"].max()
lowest_score = data["Score"].min()

# Step 3: Create PDF
pdf = FPDF()
pdf.add_page()

# Title Style
pdf.set_font("Arial", 'B', 16)
pdf.cell(200, 10, txt="Student Score Report", ln=True, align='C')
pdf.ln(5)

# Line Separator
pdf.set_draw_color(0, 0, 0)
pdf.line(10, 25, 200, 25)
pdf.ln(10)

# Table Header
pdf.set_font("Arial", 'B', 12)
pdf.cell(100, 10, txt="Name", border=1)
pdf.cell(50, 10, txt="Score", border=1, ln=True)

# Table Rows
pdf.set_font("Arial", size=12)
for index, row in data.iterrows():
    pdf.cell(100, 10, txt=row['Name'], border=1)
    pdf.cell(50, 10, txt=str(row['Score']), border=1, ln=True)

pdf.ln(10)
pdf.set_font("Arial", 'B', 12)
pdf.cell(200, 10, txt=f"Average Score: {average_score:.2f}", ln=True)
pdf.cell(200, 10, txt=f"Highest Score: {highest_score}", ln=True)
pdf.cell(200, 10, txt=f"Lowest Score: {lowest_score}", ln=True)

# Footer with name and date
pdf.ln(10)
pdf.set_font("Arial", 'I', 10)
today = datetime.now().strftime("%d-%m-%Y")
pdf.cell(200, 10, txt=f"Generated by Bhavy Patel on {today}", ln=True, align='R')

# Save
pdf.output("report.pdf")

print(" Styled PDF generated: report.pdf")
